version: "3"
services:
  prometheus:
    image: prom/prometheus:v3.0.0
    volumes:
      - "./prometheus:/etc/prometheus"
    networks:
      - localprom
    ports:
      - 9090:9090
  alertmanager:
    image: bitnami/alertmanager:0.27.0-debian-12-r26
    volumes:
      - "./alertmanager/conf:/opt/bitnami/alertmanager/conf"
    networks:
      - localprom
    ports:
      - 9093:9093
  local-exporter:
    build: local-exporter
    networks:
      - localprom
    ports:
      - 8000:8000
    env_file:
      - .env
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - localprom

networks:
  localprom:
    driver: bridge

volumes:
  grafana-storage:
    driver: local
