alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - 'alertmanager:9093'
global:
  scrape_interval: 5s
rule_files:
  - /etc/prometheus/allert_rules.yml
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090
 - job_name: local-exporter
   static_configs:
    - targets:
       - local-exporter:8000
